services:

  db:
    image: postgres:16 
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - antworker

  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - antworker

volumes:
  postgres_data:

networks:
  antworker: