[project]
name = "anthill"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=2.3.3,<2.4",
    "python-dotenv>=1.1.0,<2",
    "sqlalchemy==2.0.39",
    "psycopg2==2.9.10",
    "alembic>=1.15.2",
    "alembic-postgresql-enum",
]

[tool.setuptools]
packages = ["anthill"]
